using System;

namespace SharpAstrology.Enums;

public enum Ayanamsas
{
    FagenBradley,
    Lahiri,
    Deluce,
    Raman,
    Ushashashi,
    Krishnamurti,
    DjwhalKhul,
    Yukteshwar,
    JNBhasin,
    BabylonianKugler1,
    BabylonianKugler2,
    BabylonianKugler3,
    BabylonianHuber,
    BabylonianEtaPiscium,
    BabylonianAldebaran15Tau,
    Hipparchos,
    Sassanian,
    GalacticCenter0Sag,
    J2000,
    J1900,
    B1950,
    Suryasiddhanta,
    SuryasiddhantaMeanSun,
    Aryabhata,
    AryabhataMeanSun,
    SSRevati,
    SSCitra,
    TrueCitra,
    TrueRevati,
    TruePushyaPvrnRao,
    GalacticCenterGilBrand,
    GalacticEquatorIAU1958,
    GalacticEquator,
    GalacticEquatorMidMula,
    SkydramMardyks,
    TrueMulaChandraHari,
    GalacticCenterMidMula,
    Aryabhata522,
    BabylonianBritton,
    VedicSheoran,
    CochraneGalCenter0Cap,
    GalacticEquatorFiorenza,
    VettiusValens,
    Lahiri1940,
    LahiriVP285,
    KrishnamurtiSenthilathiban,
    LahiriICRC,
    UserDefined
}

public static class AyanamsaExtensionMethods
{
    public static string ToName(this Ayanamsas ayanamsa)
    {
        return ayanamsa switch
        {
            Ayanamsas.FagenBradley => "Fagen / Bradley",
            Ayanamsas.Lahiri => "Lahiri",
            Ayanamsas.Deluce => "Deluce",
            Ayanamsas.Raman => "Raman",
            Ayanamsas.Ushashashi => "Ushashashi",
            Ayanamsas.Krishnamurti => "Krishnamurti",
            Ayanamsas.DjwhalKhul => "DjwhalKhul",
            Ayanamsas.Yukteshwar => "Yukteshwar",
            Ayanamsas.JNBhasin => "J. N. Bhasin",
            Ayanamsas.BabylonianKugler1 => "Babylonian: Kugler 1",
            Ayanamsas.BabylonianKugler2 => "Babylonian: Kugler 2",
            Ayanamsas.BabylonianKugler3 => "Babylonian: Kugler 3",
            Ayanamsas.BabylonianHuber => "Babylonian: Huber",
            Ayanamsas.BabylonianEtaPiscium => "Babylonian: Eta Piscium",
            Ayanamsas.BabylonianAldebaran15Tau => "Babylonian: Aldebaran 15deg Tau",
            Ayanamsas.Hipparchos => "Hipparchos",
            Ayanamsas.Sassanian => "Sassanian",
            Ayanamsas.GalacticCenter0Sag => "Galactic center: 0 Sag",
            Ayanamsas.J2000 => "J2000",
            Ayanamsas.J1900 => "J1900",
            Ayanamsas.B1950 => "B1950",
            Ayanamsas.Suryasiddhanta => "Suryasiddhanta",
            Ayanamsas.SuryasiddhantaMeanSun => "Suryasiddhanta, mean sun",
            Ayanamsas.Aryabhata => "Aryabhata",
            Ayanamsas.AryabhataMeanSun => "Aryabhata, mean sun",
            Ayanamsas.SSRevati => "SS Revati",
            Ayanamsas.SSCitra => "SS Citra",
            Ayanamsas.TrueCitra => "True Citra",
            Ayanamsas.TrueRevati => "True Revati",
            Ayanamsas.TruePushyaPvrnRao => "True Pushya",
            Ayanamsas.GalacticCenterGilBrand => "Galactic center",
            Ayanamsas.GalacticEquatorIAU1958 => "Galactic equator IAU1958",
            Ayanamsas.GalacticEquator => "Galactic equator",
            Ayanamsas.GalacticEquatorMidMula => "Galactic equator mid Mula",
            Ayanamsas.SkydramMardyks => "Skydram Mardyks",
            Ayanamsas.TrueMulaChandraHari => "True Mula",
            Ayanamsas.GalacticCenterMidMula => "Galactic center mid Mula",
            Ayanamsas.Aryabhata522 => "Aryabhata 522",
            Ayanamsas.BabylonianBritton => "Babylonian: Britton",
            Ayanamsas.VedicSheoran => "Vedic (Sheoran)",
            Ayanamsas.CochraneGalCenter0Cap => "Galactic center 0 Cap",
            Ayanamsas.GalacticEquatorFiorenza => "Galactic equator Fiorenza",
            Ayanamsas.VettiusValens => "Vettius Valens",
            Ayanamsas.Lahiri1940 => "Lahiri 1940",
            Ayanamsas.LahiriVP285 => "Lahiri VP285",
            Ayanamsas.KrishnamurtiSenthilathiban => "Krishnamurti-Senthilathiban",
            Ayanamsas.LahiriICRC => "Lahiri ICRC",
            Ayanamsas.UserDefined => "User defined",
            _ => throw new ArgumentOutOfRangeException(nameof(ayanamsa), ayanamsa, $"Missing implementation of {nameof(ayanamsa)}")
        };
    }
}